# Generated by Django 6.0.4 on 2026-04-11 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('port', models.IntegerField(default=80)),
                ('technologie', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('erreur', 'Erreur')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webapps', to='servers.server')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
