# Generated by Django 6.0.4 on 2026-04-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('datacenter', models.CharField(max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('total_unites_u', models.PositiveIntegerField(default=42)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['datacenter', 'nom'],
            },
        ),
    ]
