# Generated by Django 6.0.4 on 2026-06-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='category',
            field=models.CharField(choices=[('SERVER', 'Serveur'), ('SSL', 'Certificat SSL'), ('SOFTWARE', 'Logiciel'), ('LOGIN', 'Connexion'), ('OTHER', 'Autre')], default='OTHER', max_length=50),
        ),
    ]
