# Generated by Django 6.0.4 on 2026-04-11 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=255)),
                ('emetteur', models.CharField(max_length=150)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats', to='webapps.webapplication')),
            ],
            options={
                'ordering': ['date_expiration'],
            },
        ),
    ]
