# Generated by Django 6.0.4 on 2026-04-11 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=50)),
                ('editeur', models.CharField(blank=True, max_length=100)),
                ('type_licence', models.CharField(choices=[('gratuite', 'Gratuite'), ('open-source', 'Open-source'), ('commerciale', 'Commerciale'), ('entreprise', 'Entreprise')], default='commerciale', max_length=50)),
                ('cle_licence', models.CharField(blank=True, max_length=255, null=True)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logiciels', to='servers.server')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
