# Generated by Django 6.0.4 on 2026-04-11 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('adresse_ip_secondaire', models.GenericIPAddressField(blank=True, null=True)),
                ('systeme_exploitation', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('physique', 'Physique'), ('virtuel', 'Virtuel')], default='virtuel', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('maintenance', 'En Maintenance'), ('alerte', 'En Alerte')], default='actif', max_length=20)),
                ('cpu_coeurs', models.IntegerField()),
                ('cpu_modele', models.CharField(blank=True, max_length=150)),
                ('ram_go', models.IntegerField()),
                ('stockage_go', models.IntegerField()),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serveurs', to='racks.rack')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ServerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='servers.server')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
