# Generated by Django 6.0.4 on 2026-04-13 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermetric',
            name='cpu_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='server_snapshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='servers.server')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
